#!/bin/sh -e
mkdir wine64-build
mkdir wine32-build
cd wine64-build
../configure --prefix=/usr --enable-win64
make
cd ../wine32-build
# TODO: Do I need special 32 bit libraries for the below? On KISS it appears
# that /usr/lib64 and /usr/lib are the same, which implies to me the PKGCONFIG
# specification below that they recommend in their build guide is not doing
# anything for me. Mayhaps I need a /usr/lib32, plus I need to add a bunch of
# 32-bit libraries to dgkiss and install them there?
PKG_CONFIG_PATH=/usr/lib/pkgconfig ../configure --with-wine64=wine64-build
make
make DESTDIR="$1" install
cd ../wine64-build
make DESTDIR="$1" install
