#!/bin/sh -e

export DESTDIR="$1"

# Don't build tests.
sed -i "/subdir('tests')/d" meson.build

meson \
    --prefix=/usr \
    -Dglx=enabled \
    -Dx11=enabled \
    . output

ninja -C output
ninja -C output install
