#!/bin/sh -e
git submodule init
git submodule update
echo "$1"
echo "$HOME"
echo "$1/$HOME"
mkdir -p "$1/$HOME/.multimc"
mkdir build
cd build
echo "$1/$HOME/.multimc"
cmake -DCMAKE_INSTALL_PREFIX="$HOME/.multimc" ../
make install
ls "$1/$HOME/.multimc"
cd ..
mkdir -p "$1/usr/bin/"
echo -e "#!/bin/sh -e\ncd \$HOME/.multimc && ./MultiMC" >"$1/usr/bin/MultiMC"
