#!/bin/sh -e
patch -p1 < minecraft-wayland/0001-set-O_NONBLOCK-on-repeat-timerfd.patch
patch -p1 < minecraft-wayland/0002-Don-t-crash-on-calls-to-focus-or-icon.patch
patch -p1 < minecraft-wayland/0003-fix-broken-opengl-screenshots-on-mutter.patch
patch -p1 < minecraft-wayland/0004-Do-not-crash-on-window-position-set.patch
cmake -DBUILD_SHARED_LIBS=ON -DGLFW_USE_WAYLAND=1 .
make
make DESTDIR="$1" install
mv -v "$1/usr/local/include" "$1/usr/include"
mv -v "$1/usr/local/lib64" "$1/usr/lib"
rm -rf "$1/usr/local"
